import * as React from 'react';

export type FeatherIcon = (props: React.SVGProps<SVGSVGElement> & {
    children?: React.ReactNode;
    size?: string | number;
    color?: string;
    title?: string;
}) => React.ReactElement | null;

export const FiActivity: FeatherIcon;
export const FiAlertCircle: FeatherIcon;
export const FiAlertTriangle: FeatherIcon;
export const FiAward: FeatherIcon;
export const FiBarChart2: FeatherIcon;
export const FiCheck: FeatherIcon;
export const FiCheckCircle: FeatherIcon;
export const FiChevronDown: FeatherIcon;
export const FiChevronRight: FeatherIcon;
export const FiClipboard: FeatherIcon;
export const FiClock: FeatherIcon;
export const FiCloud: FeatherIcon;
export const FiCompass: FeatherIcon;
export const FiCopy: FeatherIcon;
export const FiCreditCard: FeatherIcon;
export const FiCpu: FeatherIcon;
export const FiDollarSign: FeatherIcon;
export const FiDownload: FeatherIcon;
export const FiEdit: FeatherIcon;
export const FiEdit2: FeatherIcon;
export const FiExternalLink: FeatherIcon;
export const FiEye: FeatherIcon;
export const FiFileText: FeatherIcon;
export const FiFilter: FeatherIcon;
export const FiFolder: FeatherIcon;
export const FiGift: FeatherIcon;
export const FiGrid: FeatherIcon;
export const FiHelpCircle: FeatherIcon;
export const FiHome: FeatherIcon;
export const FiImage: FeatherIcon;
export const FiLayers: FeatherIcon;
export const FiLock: FeatherIcon;
export const FiLogOut: FeatherIcon;
export const FiMaximize2: FeatherIcon;
export const FiMenu: FeatherIcon;
export const FiMonitor: FeatherIcon;
export const FiPlus: FeatherIcon;
export const FiRefreshCw: FeatherIcon;
export const FiRepeat: FeatherIcon;
export const FiSave: FeatherIcon;
export const FiSearch: FeatherIcon;
export const FiSettings: FeatherIcon;
export const FiShare2: FeatherIcon;
export const FiShield: FeatherIcon;
export const FiStar: FeatherIcon;
export const FiSun: FeatherIcon;
export const FiTool: FeatherIcon;
export const FiTrash2: FeatherIcon;
export const FiTrendingDown: FeatherIcon;
export const FiTrendingUp: FeatherIcon;
export const FiType: FeatherIcon;
export const FiUpload: FeatherIcon;
export const FiUser: FeatherIcon;
export const FiUserCheck: FeatherIcon;
export const FiUsers: FeatherIcon;
export const FiVideo: FeatherIcon;
export const FiX: FeatherIcon;
export const FiXCircle: FeatherIcon;
export const FiZap: FeatherIcon;
